/**
 * Official curriculum data — Master Informatique Visuelle (IV), USTHB.
 * Source: Fiche technique MIV 2021 + Cahier des charges "Master académique MIV"
 * https://finfo.usthb.dz/pages/Master-Informatique-Visuelle
 */

export const PROGRAM = {
  university: 'Université des Sciences et de la Technologie Houari Boumediene',
  universityShort: 'USTHB',
  faculty_fr: "Faculté d'Électronique et d'Informatique — Département Informatique",
  faculty_en: 'Faculty of Electronics and Computer Science — Computer Science Department',
  degree_fr: 'Master Académique — Informatique Visuelle (IV)',
  degree_en: 'Academic Master — Visual Computing (IV)',
  domain: 'MI',
  filiere: 'Informatique',
  accreditation: '2021-2022',
  links: {
    ficheTechnique: 'https://finfo.usthb.dz/storage/disk/FichTechniqueMIV2021-1.pdf',
    cahierDesCharges: 'https://finfo.usthb.dz/storage/disk/Master-academique-MIV-2020FINAL_num.pdf',
    page: 'https://finfo.usthb.dz/pages/Master-Informatique-Visuelle',
    campusVirtuel: 'https://campusvirtuel.usthb.dz/',
    ent: 'https://ent.usthb.dz/',
    emploiDuTemps: 'https://finfo.usthb.dz/etudes/emploi-du-temps',
    examens: 'https://finfo.usthb.dz/etudes/planning-des-examens/',
    deliberations: 'https://finfo.usthb.dz/etudes/délibérations/',
    bibliotheque: 'https://bu.usthb.dz/',
    pfe: 'https://finfo.usthb.dz/stage/-pfe-licence-master',
  },
};

/* type: F = fondamentale, M = méthodologie, D = découverte, P = projet */
export const SEMESTERS = [
  {
    number: 1,
    label_fr: 'Semestre 1',
    label_en: 'Semester 1',
    credits: 30,
    coef: 18,
    vhs: 336,
    weekly: { c: '9h00', td: '4h30', tp: '10h30' },
    units: [
      {
        code: 'UEF1.1',
        type: 'F',
        label_fr: 'Unité fondamentale 1.1',
        label_en: 'Core unit 1.1',
        credits: 10,
        coef: 6,
        vhs: 105,
        courses: [
          {
            code: 'ALGC',
            title_fr: 'Algorithmique Avancée et Complexité',
            title_en: 'Advanced Algorithms and Complexity',
            credits: 5,
            coef: 3,
            vhs: 63,
            c: 1.5,
            td: 1.5,
            tp: 1.5,
            continu: 0.4,
            examen: 0.6,
            teachers: 'Dr. Nacéra Bensaou',
            summary_fr:
              "Construire des solutions algorithmiques, évaluer leur complexité et classer les problèmes (P, NP, NP-complets) à travers des cas issus des réseaux, des bases de données et de l'algorithmique du texte.",
            summary_en:
              'Design algorithmic solutions, evaluate their complexity and classify problems (P, NP, NP-complete) through cases drawn from networks, databases and string algorithms.',
            prereq_fr: 'Programmation, algorithmes itératifs et récursifs, structures de données fondamentales.',
            prereq_en: 'Programming, iterative and recursive algorithms, fundamental data structures.',
            chapters: [
              ['Introduction', 'Introduction'],
              ["Bases de l'analyse d'un algorithme", 'Foundations of algorithm analysis'],
              ["Calcul de la complexité d'un algorithme", 'Computing algorithmic complexity'],
              ['Stratégies de résolution de problèmes', 'Problem-solving strategies'],
              ["Structures de données et comparaison d'algorithmes", 'Data structures and algorithm comparison'],
              ['Classes de problèmes : décidabilité, P, NP, NP-complet', 'Problem classes: decidability, P, NP, NP-complete'],
            ],
            links: [
              ['MIT 6.006 — Introduction to Algorithms', 'https://ocw.mit.edu/courses/6-006-introduction-to-algorithms-spring-2020/', 'course'],
              ['VisuAlgo — algorithmes animés', 'https://visualgo.net/en', 'tool'],
              ['Complexity Zoo', 'https://complexityzoo.net/Complexity_Zoo', 'reference'],
            ],
          },
          {
            code: 'RP',
            title_fr: 'Résolution de Problèmes',
            title_en: 'Problem Solving',
            credits: 5,
            coef: 3,
            vhs: 42,
            c: 1.5,
            td: 0,
            tp: 1.5,
            continu: 0.4,
            examen: 0.6,
            teachers: 'Prof. S. Larabi, Prof. H. Azzoune',
            summary_fr:
              "Bases de l'intelligence artificielle symbolique : modélisation, recherche de solutions (A*), algorithmes de jeux, méta-heuristiques et satisfaction de contraintes.",
            summary_en:
              'Foundations of symbolic AI: modelling, solution search (A*), game algorithms, metaheuristics and constraint satisfaction.',
            prereq_fr: 'Aucun prérequis.',
            prereq_en: 'No prerequisites.',
            chapters: [
              ["Introduction à l'Intelligence Artificielle", 'Introduction to Artificial Intelligence'],
              ['Résolution de problèmes de planification (algorithme A*)', 'Planning problems (A* algorithm)'],
              ['Algorithmes pour les jeux : Min-Max, Alpha-Bêta', 'Game algorithms: Min-Max, Alpha-Beta'],
              ['Les méta-heuristiques', 'Metaheuristics'],
              ['Problèmes de satisfaction de contraintes (CSP)', 'Constraint satisfaction problems (CSP)'],
            ],
            links: [
              ['UC Berkeley CS188 — Intro to AI', 'https://inst.eecs.berkeley.edu/~cs188/', 'course'],
              ['Russell & Norvig — AIMA resources', 'https://aima.cs.berkeley.edu/', 'reference'],
              ['Red Blob Games — A* interactif', 'https://www.redblobgames.com/pathfinding/a-star/introduction.html', 'tool'],
            ],
          },
        ],
      },
      {
        code: 'UEF1.2',
        type: 'F',
        label_fr: 'Unité fondamentale 1.2',
        label_en: 'Core unit 1.2',
        credits: 8,
        coef: 6,
        vhs: 105,
        courses: [
          {
            code: 'ABD',
            title_fr: 'Architecture des Bases de Données',
            title_en: 'Database Architecture',
            credits: 4,
            coef: 3,
            vhs: 42,
            c: 1.5,
            td: 0,
            tp: 1.5,
            continu: 0.4,
            examen: 0.6,
            teachers: 'Prof. Kamel Boukhalfa, Prof. Aicha Mokhtari-Aissani',
            summary_fr:
              "Maîtriser l'architecture interne des SGBD et l'administration d'une base après sa création : métadonnées, optimisation de requêtes, concurrence et reprise.",
            summary_en:
              'Master DBMS internals and database administration after creation: metadata, query optimisation, concurrency control and recovery.',
            prereq_fr: 'Conception, création et utilisation d\'une base de données.',
            prereq_en: 'Database design, creation and usage.',
            chapters: [
              ['Généralités sur les SGBD, concepts et architecture', 'DBMS overview, concepts and architecture'],
              ['Les métadonnées : structure et gestion', 'Metadata: structure and management'],
              ['Contraintes et triggers', 'Constraints and triggers'],
              ['Optimisation des requêtes', 'Query optimisation'],
              ['Gestion des accès concurrents : transactions et protocoles', 'Concurrency control: transactions and protocols'],
              ['Sécurité : reprises, journal, sauvegarde et droits', 'Security: recovery, journaling, backup and privileges'],
            ],
            links: [
              ['Use The Index, Luke — indexation SQL', 'https://use-the-index-luke.com/', 'reference'],
              ['PostgreSQL — documentation officielle', 'https://www.postgresql.org/docs/current/', 'reference'],
              ['CMU 15-445 — Database Systems', 'https://15445.courses.cs.cmu.edu/', 'course'],
            ],
          },
          {
            code: 'SE',
            title_fr: "Systèmes d'Exploitation",
            title_en: 'Operating Systems',
            credits: 4,
            coef: 3,
            vhs: 63,
            c: 1.5,
            td: 1.5,
            tp: 1.5,
            continu: 0.4,
            examen: 0.6,
            teachers: 'Dr. Mahfoud Benchaiba',
            summary_fr:
              "Approfondir les concepts de conception d'un système d'exploitation et la programmation système : fichiers, protection, synchronisation, IPC et interblocage.",
            summary_en:
              'Deepen operating-system design concepts and system programming: file systems, protection, synchronisation, IPC and deadlock.',
            prereq_fr: "Notions de base d'un système d'exploitation.",
            prereq_en: 'Basic operating-system concepts.',
            chapters: [
              ['Systèmes de fichiers', 'File systems'],
              ['Protection et sécurité', 'Protection and security'],
              ['Synchronisation des processus', 'Process synchronisation'],
              ['Communication entre processus', 'Inter-process communication'],
              ['Interblocage : prévention, évitement, détection', 'Deadlock: prevention, avoidance, detection'],
            ],
            links: [
              ['OSTEP — Operating Systems: Three Easy Pieces', 'https://pages.cs.wisc.edu/~remzi/OSTEP/', 'reference'],
              ['Linux man-pages', 'https://man7.org/linux/man-pages/', 'reference'],
              ['Linux Kernel Labs', 'https://linux-kernel-labs.github.io/', 'lab'],
            ],
          },
        ],
      },
      {
        code: 'UEM1.1',
        type: 'M',
        label_fr: 'Unité méthodologie 1.1',
        label_en: 'Methodology unit 1.1',
        credits: 9,
        coef: 6,
        vhs: 105,
        courses: [
          {
            code: 'CM',
            title_fr: 'Communication Multimédia',
            title_en: 'Multimedia Communication',
            credits: 4,
            coef: 3,
            vhs: 42,
            c: 1.5,
            td: 0,
            tp: 1.5,
            continu: 0.4,
            examen: 0.6,
            teachers: 'Prof. Slimane Larabi, Dr. Afifa Dahmane',
            summary_fr:
              "Fondements des technologies multimédia : compression, transport temps réel et sécurité, pour produire une application intégrant image, vidéo, son et texte.",
            summary_en:
              'Foundations of multimedia technologies: compression, real-time transport and security, in order to build an application combining image, video, audio and text.',
            prereq_fr: 'Algorithmique, programmation orientée objet, HTML/XML.',
            prereq_en: 'Algorithms, object-oriented programming, HTML/XML.',
            chapters: [
              ['Système multimédia : évolution et éléments de base', 'Multimedia systems: evolution and building blocks'],
              ['Compression de données (sans perte et avec perte)', 'Data compression (lossless and lossy)'],
              ['Communication temps réel : RTP, RTCP, RTSP', 'Real-time communication: RTP, RTCP, RTSP'],
              ['Sécurité des données multimédia', 'Multimedia data security'],
            ],
            links: [
              ['MDN — Media technologies on the web', 'https://developer.mozilla.org/en-US/docs/Web/Media', 'reference'],
              ['FFmpeg — documentation', 'https://ffmpeg.org/documentation.html', 'tool'],
              ['RFC 3550 — RTP', 'https://www.rfc-editor.org/rfc/rfc3550', 'reference'],
            ],
          },
          {
            code: 'TAI',
            title_fr: "Traitement et Analyse d'Images",
            title_en: 'Image Processing and Analysis',
            credits: 5,
            coef: 3,
            vhs: 63,
            c: 1.5,
            td: 1.5,
            tp: 1.5,
            continu: 0.4,
            examen: 0.6,
            teachers: 'Dr. Nadia Baha',
            summary_fr:
              "L'ensemble des techniques de traitement d'image, de la formation du signal aux descripteurs et à la segmentation, en vue d'applications de sécurité, de contrôle ou de biométrie.",
            summary_en:
              'The full image-processing toolbox, from signal formation to descriptors and segmentation, targeting security, inspection and biometrics applications.',
            prereq_fr: 'Algorithmique.',
            prereq_en: 'Algorithms.',
            chapters: [
              ["Formation et transformation de l'image", 'Image formation and transformation'],
              ['Prétraitement et extraction de primitives', 'Pre-processing and feature extraction'],
              ['Caractéristiques des images : couleur, texture, forme', 'Image characteristics: colour, texture, shape'],
              ['Détection de contours et segmentation', 'Edge detection and segmentation'],
              ["Analyse d'images : flot optique, suivi, filtres de Kalman", 'Image analysis: optical flow, tracking, Kalman filters'],
            ],
            links: [
              ['OpenCV — documentation', 'https://docs.opencv.org/', 'tool'],
              ['scikit-image — user guide', 'https://scikit-image.org/docs/stable/', 'tool'],
              ['Szeliski — Computer Vision (livre libre)', 'https://szeliski.org/Book/', 'reference'],
            ],
          },
        ],
      },
      {
        code: 'UED1.1',
        type: 'D',
        label_fr: 'Unité découverte 1.1',
        label_en: 'Discovery unit 1.1',
        credits: 3,
        coef: 1,
        vhs: 21,
        courses: [
          {
            code: 'ANG1',
            title_fr: 'Anglais 1',
            title_en: 'English 1',
            credits: 3,
            coef: 1,
            vhs: 21,
            c: 0,
            td: 0,
            tp: 1.5,
            continu: 0.4,
            examen: 0.6,
            teachers: '—',
            summary_fr:
              "Lire des articles de recherche en informatique, s'exprimer et rédiger en anglais scientifique.",
            summary_en:
              'Read computer-science research papers, speak and write in scientific English.',
            prereq_fr: 'Anglais général niveau licence.',
            prereq_en: 'Undergraduate-level general English.',
            chapters: [],
            links: [
              ['Academic Phrasebank — Manchester', 'https://www.phrasebank.manchester.ac.uk/', 'reference'],
              ['Cambridge Dictionary', 'https://dictionary.cambridge.org/', 'tool'],
            ],
          },
        ],
      },
    ],
  },
  {
    number: 2,
    label_fr: 'Semestre 2',
    label_en: 'Semester 2',
    credits: 30,
    coef: 18,
    vhs: 336,
    weekly: { c: '10h30', td: '1h30', tp: '12h00' },
    units: [
      {
        code: 'UEF2.1',
        type: 'F',
        label_fr: 'Unité fondamentale 2.1',
        label_en: 'Core unit 2.1',
        credits: 8,
        coef: 5,
        vhs: 84,
        courses: [
          {
            code: 'FD',
            title_fr: 'Fouille de Données',
            title_en: 'Data Mining',
            credits: 4, coef: 3, vhs: 42, c: 1.5, td: 0, tp: 1.5, continu: 0.4, examen: 0.6,
            teachers: 'Dr. Hamid Necir, Prof. Habiba Drias',
            summary_fr: "Techniques de fouille de données sous l'angle algorithmique et logiciel : apprentissage supervisé et non supervisé, processus complet du nettoyage à la validation.",
            summary_en: 'Data-mining techniques from an algorithmic and software angle: supervised and unsupervised learning, full pipeline from cleaning to validation.',
            prereq_fr: 'Notions de bases de données.', prereq_en: 'Database fundamentals.',
            chapters: [
              ['Introduction à la fouille de données', 'Introduction to data mining'],
              ['Le processus de la fouille de données', 'The data-mining process'],
              ['Techniques : clustering, règles, arbres, réseaux bayésiens', 'Techniques: clustering, rules, trees, Bayesian networks'],
              ['Text mining et web mining', 'Text mining and web mining'],
            ],
            links: [
              ['scikit-learn — user guide', 'https://scikit-learn.org/stable/user_guide.html', 'tool'],
              ['Tan, Steinbach & Kumar — Introduction to Data Mining', 'https://www-users.cse.umn.edu/~kumar001/dmbook/index.php', 'reference'],
            ],
          },
          {
            code: 'AD',
            title_fr: 'Analyse de Données',
            title_en: 'Data Analysis',
            credits: 4, coef: 2, vhs: 42, c: 1.5, td: 0, tp: 1.5, continu: 0.4, examen: 0.6,
            teachers: 'Dr. Nacéra Laiche, Prof. Amar Aissani',
            summary_fr: "Méthodes factorielles et de classification pour extraire des paramètres aidant à l'interprétation et à la classification des données.",
            summary_en: 'Factor-analysis and clustering methods to extract parameters supporting data interpretation and classification.',
            prereq_fr: 'Notions de statistiques.', prereq_en: 'Statistics fundamentals.',
            chapters: [
              ['Introduction et types de données', 'Introduction and data types'],
              ['Analyse en Composantes Principales (ACP)', 'Principal Component Analysis (PCA)'],
              ['Analyses factorielles', 'Factor analysis'],
              ['Analyse Factorielle des Correspondances (AFC)', 'Correspondence Analysis (CA)'],
              ['AFC Multiples (AFCM)', 'Multiple Correspondence Analysis (MCA)'],
              ['Classification hiérarchique et centres mobiles', 'Hierarchical clustering and k-means'],
            ],
            links: [
              ['FactoMineR — analyse factorielle avec R', 'http://factominer.free.fr/', 'tool'],
              ['An Introduction to Statistical Learning', 'https://www.statlearning.com/', 'reference'],
            ],
          },
        ],
      },
      {
        code: 'UEF2.2',
        type: 'F',
        label_fr: 'Unité fondamentale 2.2',
        label_en: 'Core unit 2.2',
        credits: 10,
        coef: 7,
        vhs: 126,
        courses: [
          {
            code: 'VA',
            title_fr: 'Vision Artificielle',
            title_en: 'Computer Vision',
            credits: 4, coef: 3, vhs: 42, c: 1.5, td: 0, tp: 1.5, continu: 0.4, examen: 0.6,
            teachers: 'Prof. Slimane Larabi',
            summary_fr: "Reconstruire la scène 3D et comprendre le contenu d'une scène statique ou dynamique à partir d'images.",
            summary_en: 'Reconstruct 3D scenes and interpret static or dynamic scene content from images.',
            prereq_fr: "Traitement d'image, algorithmique.", prereq_en: 'Image processing, algorithms.',
            chapters: [
              ['Modèle de caméra, calibration, géométrie épipolaire', 'Camera model, calibration, epipolar geometry'],
              ['Reconstruction 3D (stéréo, ombre, texture, mouvement)', '3D reconstruction (stereo, shading, texture, motion)'],
              ['Reconnaissance : objets, visages, catégories', 'Recognition: objects, faces, categories'],
              ["Applications : CBIR, RDF, activités humaines, scènes", 'Applications: CBIR, pattern recognition, human activity, scenes'],
            ],
            links: [
              ['Szeliski — Computer Vision: Algorithms and Applications', 'https://szeliski.org/Book/', 'reference'],
              ['Stanford CS231n', 'https://cs231n.github.io/', 'course'],
            ],
          },
          {
            code: 'RES',
            title_fr: 'Réseaux',
            title_en: 'Computer Networks',
            credits: 3, coef: 2, vhs: 42, c: 1.5, td: 0, tp: 1.5, continu: 0.4, examen: 0.6,
            teachers: 'Dr. Youcef Zafoune, Khaled Zeraoulia',
            summary_fr: "Installation, configuration et routage optimal dans les architectures réseaux, jusqu'aux réseaux étendus et VPN.",
            summary_en: 'Installation, configuration and optimal routing in network architectures, up to wide-area networks and VPNs.',
            prereq_fr: 'TCP/IP, réseaux locaux, systèmes d\'exploitation.', prereq_en: 'TCP/IP, LANs, operating systems.',
            chapters: [
              ['Couche application et modèle client/serveur', 'Application layer and client/server model'],
              ['Réseaux locaux : Ethernet', 'Local networks: Ethernet'],
              ['Protocoles TCP/IP', 'TCP/IP protocols'],
              ['Routage : VLSM, RIP, OSPF, BGP', 'Routing: VLSM, RIP, OSPF, BGP'],
              ['Réseaux étendus : PPP, Frame Relay, VPN', 'Wide-area networks: PPP, Frame Relay, VPN'],
            ],
            links: [
              ['RFC Editor', 'https://www.rfc-editor.org/', 'reference'],
              ['Practical Networking', 'https://www.practicalnetworking.net/', 'reference'],
            ],
          },
          {
            code: 'CGOC',
            title_fr: 'Compilation : Génération et Optimisation de Code',
            title_en: 'Compilation: Code Generation and Optimisation',
            credits: 3, coef: 2, vhs: 63, c: 1.5, td: 1.5, tp: 1.5, continu: 0.4, examen: 0.6,
            teachers: 'Prof. M. Boukala',
            summary_fr: "Traduction dirigée par la syntaxe, code intermédiaire, optimisation, allocation mémoire et génération de code objet (TP avec lex et yacc).",
            summary_en: 'Syntax-directed translation, intermediate code, optimisation, memory allocation and object-code generation (labs with lex and yacc).',
            prereq_fr: 'Analyse lexicale et analyse syntaxique.', prereq_en: 'Lexical and syntax analysis.',
            chapters: [
              ['Rappels : analyse lexicale, syntaxique, traduction dirigée', 'Review: lexical, syntax analysis, syntax-directed translation'],
              ['Allocation, substitution', 'Allocation, substitution'],
              ["Organisation des données à l'exécution", 'Run-time data organisation'],
              ['Optimisation du code', 'Code optimisation'],
              ['Génération de code objet', 'Object-code generation'],
            ],
            links: [
              ['Crafting Interpreters', 'https://craftinginterpreters.com/', 'reference'],
              ['LLVM — documentation', 'https://llvm.org/docs/', 'tool'],
            ],
          },
        ],
      },
      {
        code: 'UEM2.1',
        type: 'M',
        label_fr: 'Unité méthodologie 2.1',
        label_en: 'Methodology unit 2.1',
        credits: 9,
        coef: 5,
        vhs: 105,
        courses: [
          {
            code: 'CJRV',
            title_fr: 'Conception de Jeux et Réalité Virtuelle',
            title_en: 'Game Design and Virtual Reality',
            credits: 4, coef: 2, vhs: 42, c: 1.5, td: 0, tp: 1.5, continu: 0.4, examen: 0.6,
            teachers: 'Prof. Slimane Larabi, Dr. Amel Ourahmoune',
            summary_fr: "Éléments formels et techniques de la conception de jeux vidéo sur mobile, PC et console, et fondements de la réalité virtuelle.",
            summary_en: 'Formal and technical elements of video-game design on mobile, PC and console, plus virtual-reality foundations.',
            prereq_fr: 'Algorithmique.', prereq_en: 'Algorithms.',
            chapters: [
              ['Conception et développement de jeux : principes de base', 'Game design and development: fundamentals'],
              ['HTML5 et JavaScript : éléments de base', 'HTML5 and JavaScript essentials'],
              ['Lutins (sprites) et tuiles (tiles)', 'Sprites and tiles'],
              ['Détection de collision', 'Collision detection'],
              ['Rendu graphique et son', 'Graphics rendering and audio'],
              ['La réalité virtuelle : modèles, interaction, périphériques', 'Virtual reality: models, interaction, devices'],
              ['Réalité virtuelle distribuée et mobile', 'Distributed and mobile virtual reality'],
            ],
            links: [
              ['MDN — Game development', 'https://developer.mozilla.org/en-US/docs/Games', 'reference'],
              ['Unity — manual', 'https://docs.unity3d.com/Manual/index.html', 'tool'],
              ['Godot Engine — docs', 'https://docs.godotengine.org/', 'tool'],
            ],
          },
          {
            code: 'AA',
            title_fr: 'Réseaux de Neurones et Apprentissage Automatique',
            title_en: 'Neural Networks and Machine Learning',
            credits: 5, coef: 3, vhs: 42, c: 1.5, td: 0, tp: 1.5, continu: 0.4, examen: 0.6,
            teachers: 'Prof. Ahmed Guessoum, Dr. Zahia Tamen',
            summary_fr: "Des concepts d'apprentissage aux réseaux profonds : arbres de décision, perceptron, rétropropagation, CNN, RNN, SVM et apprentissage par renforcement.",
            summary_en: 'From learning concepts to deep networks: decision trees, perceptron, backpropagation, CNNs, RNNs, SVMs and reinforcement learning.',
            prereq_fr: 'Algorithmique.', prereq_en: 'Algorithms.',
            chapters: [
              ["Introduction et conception d'un système d'apprentissage", 'Introduction and designing a learning system'],
              ['Apprentissage de concepts et biais inductif', 'Concept learning and inductive bias'],
              ['Arbres de décision : entropie, ID3, élagage', 'Decision trees: entropy, ID3, pruning'],
              ['Réseaux de neurones peu profonds (perceptron, rétropropagation)', 'Shallow neural networks (perceptron, backpropagation)'],
              ['Réseaux profonds : CNN, LSTM, GRU, attention', 'Deep networks: CNN, LSTM, GRU, attention'],
              ['Classificateurs à base d\'instances et apprentissage bayésien', 'Instance-based classifiers and Bayesian learning'],
              ['SVM et apprentissage par renforcement', 'SVMs and reinforcement learning'],
            ],
            links: [
              ['Dive into Deep Learning', 'https://d2l.ai/', 'reference'],
              ['Deep Learning Book — Goodfellow et al.', 'https://www.deeplearningbook.org/', 'reference'],
              ['scikit-learn — supervised learning', 'https://scikit-learn.org/stable/supervised_learning.html', 'tool'],
            ],
          },
        ],
      },
      {
        code: 'UED2.1',
        type: 'D',
        label_fr: 'Unité découverte 2.1',
        label_en: 'Discovery unit 2.1',
        credits: 3, coef: 1, vhs: 21,
        courses: [
          {
            code: 'ANG2',
            title_fr: 'Anglais 2',
            title_en: 'English 2',
            credits: 3, coef: 1, vhs: 21, c: 0, td: 0, tp: 1.5, continu: 0.4, examen: 0.6,
            teachers: '—',
            summary_fr: "Approfondir la maîtrise de l'anglais scientifique.", summary_en: 'Deepen command of scientific English.',
            prereq_fr: 'Anglais 1.', prereq_en: 'English 1.',
            chapters: [],
            links: [['Academic Phrasebank — Manchester', 'https://www.phrasebank.manchester.ac.uk/', 'reference']],
          },
        ],
      },
    ],
  },
  {
    number: 3,
    label_fr: 'Semestre 3',
    label_en: 'Semester 3',
    credits: 30,
    coef: 18,
    vhs: 336,
    weekly: { c: '10h30', td: '1h30', tp: '12h00' },
    units: [
      {
        code: 'UEF3.1', type: 'F', label_fr: 'Unité fondamentale 3.1', label_en: 'Core unit 3.1',
        credits: 8, coef: 6, vhs: 105,
        courses: [
          {
            code: 'RC',
            title_fr: 'Représentation des Connaissances et Raisonnement',
            title_en: 'Knowledge Representation and Reasoning',
            credits: 4, coef: 3, vhs: 42, c: 1.5, td: 0, tp: 1.5, continu: 0.4, examen: 0.6,
            teachers: 'Prof. Faiza Khellaf',
            summary_fr: "Logiques classiques et non classiques, théories de l'incertain et modèles graphiques appliqués au traitement d'images.",
            summary_en: 'Classical and non-classical logics, theories of uncertainty and graphical models applied to image processing.',
            prereq_fr: 'Algorithmique.', prereq_en: 'Algorithms.',
            chapters: [
              ['Logiques classiques : propositions et prédicats', 'Classical logics: propositional and predicate'],
              ['Logiques non classiques : modale, défauts, description', 'Non-classical logics: modal, default, description'],
              ["Théories de l'incertain : probabilités, Dempster-Shafer, possibilités", 'Uncertainty theories: probability, Dempster-Shafer, possibility'],
              ['Sous-ensembles flous et contrôleur flou', 'Fuzzy sets and fuzzy controllers'],
              ["Réseaux bayésiens et traitement d'images", 'Bayesian networks and image processing'],
            ],
            links: [
              ['Stanford Encyclopedia — Modal Logic', 'https://plato.stanford.edu/entries/logic-modal/', 'reference'],
              ['Description Logic — resources', 'http://dl.kr.org/', 'reference'],
            ],
          },
          {
            code: 'TJ',
            title_fr: 'Théorie des Jeux',
            title_en: 'Game Theory',
            credits: 4, coef: 3, vhs: 63, c: 1.5, td: 1.5, tp: 1.5, continu: 0.4, examen: 0.6,
            teachers: 'Dr. Djamila Dahmani',
            summary_fr: "Situations où des joueurs choisissent des stratégies dont le résultat dépend de l'ensemble des joueurs : équilibres, formes normale et extensive, jeux répétés.",
            summary_en: 'Situations where players choose strategies whose outcome depends on all players: equilibria, normal and extensive forms, repeated games.',
            prereq_fr: 'Probabilités, algorithmique.', prereq_en: 'Probability, algorithms.',
            chapters: [
              ['Introduction générale à la théorie des jeux', 'General introduction to game theory'],
              ["Représentation ordinale et fonction d'utilité", 'Ordinal representation and utility functions'],
              ["Formalisation d'un jeu : forme stratégique, équilibres de Nash", 'Game formalisation: strategic form, Nash equilibria'],
              ['Jeux sous forme extensive', 'Extensive-form games'],
              ['Analyse de comportement et théorème de Kuhn', 'Behaviour analysis and Kuhn\'s theorem'],
              ['Raffinements et jeux répétés', 'Refinements and repeated games'],
            ],
            links: [
              ['Osborne & Rubinstein — A Course in Game Theory', 'https://arielrubinstein.tau.ac.il/books/', 'reference'],
              ['Algorithmic Game Theory', 'https://www.cs.cornell.edu/courses/cs6840/', 'course'],
            ],
          },
        ],
      },
      {
        code: 'UEF3.2', type: 'F', label_fr: 'Unité fondamentale 3.2', label_en: 'Core unit 3.2',
        credits: 10, coef: 6, vhs: 126,
        courses: [
          {
            code: 'SIM',
            title_fr: "Synthèse d'Images",
            title_en: 'Computer Graphics',
            credits: 4, coef: 2, vhs: 42, c: 1.5, td: 0, tp: 1.5, continu: 0.4, examen: 0.6,
            teachers: 'Dr. Afifa Dahmane',
            summary_fr: "Techniques de l'informatique graphique : pipeline de visualisation, matériel graphique, modélisation 3D et rendu réaliste.",
            summary_en: 'Computer-graphics techniques: viewing pipeline, GPU programming, 3D modelling and realistic rendering.',
            prereq_fr: 'Algèbre linéaire, algorithmique et structures de données, C++.', prereq_en: 'Linear algebra, algorithms and data structures, C++.',
            chapters: [
              ['Transformations géométriques et coordonnées homogènes', 'Geometric transformations and homogeneous coordinates'],
              ['La visualisation : pipeline, projection, rastérisation', 'Viewing: pipeline, projection, rasterisation'],
              ['Matériel graphique, shaders, VBO/VAO', 'Graphics hardware, shaders, VBO/VAO'],
              ['Élimination des parties cachées (z-buffer, BSP, lancer de rayon)', 'Hidden-surface removal (z-buffer, BSP, ray casting)'],
              ['Modélisation 3D : surfaces, quadriques, splines, CSG', '3D modelling: surfaces, quadrics, splines, CSG'],
              ['Modélisation procédurale : fractales, systèmes de particules', 'Procedural modelling: fractals, particle systems'],
              ["L'éclairement : Phong, ombrage, transparence, tracé de rayon", 'Illumination: Phong, shading, transparency, ray tracing'],
            ],
            links: [
              ['LearnOpenGL', 'https://learnopengl.com/', 'course'],
              ['Physically Based Rendering — livre en ligne', 'https://www.pbr-book.org/', 'reference'],
              ['Ray Tracing in One Weekend', 'https://raytracing.github.io/', 'lab'],
            ],
          },
          {
            code: 'VD',
            title_fr: 'Visualisation de Données',
            title_en: 'Data Visualisation',
            credits: 3, coef: 2, vhs: 42, c: 1.5, td: 0, tp: 1.5, continu: 0.4, examen: 0.6,
            teachers: 'Prof. Slimane Larabi, Amel Ourahmoune',
            summary_fr: "Méthodes de représentation visuelle pour comprendre, communiquer et décider à partir de données complexes et massives.",
            summary_en: 'Visual representation methods to understand, communicate and decide from complex, large-scale data.',
            prereq_fr: 'Bases de données, analyse de données, C++ ou Java.', prereq_en: 'Databases, data analysis, C++ or Java.',
            chapters: [
              ['Introduction et applications de la visualisation', 'Introduction and applications of visualisation'],
              ['Visualisation des informations : perception, filtrage, rendu', 'Information visualisation: perception, filtering, rendering'],
              ['Données multidimensionnelles et dynamiques', 'Multidimensional and dynamic data'],
              ['Visualisation avec R et ggplot2', 'Visualisation with R and ggplot2'],
              ['Visualisation tridimensionnelle', 'Three-dimensional visualisation'],
              ['Étude des outils de visualisation', 'Survey of visualisation tools'],
            ],
            links: [
              ['D3.js', 'https://d3js.org/', 'tool'],
              ['Fundamentals of Data Visualization — Wilke', 'https://clauswilke.com/dataviz/', 'reference'],
              ['ggplot2 — reference', 'https://ggplot2.tidyverse.org/', 'tool'],
            ],
          },
          {
            code: 'GPR',
            title_fr: 'Gestion de Projet',
            title_en: 'Project Management',
            credits: 3, coef: 2, vhs: 42, c: 1.5, td: 0, tp: 1.5, continu: 0.4, examen: 0.6,
            teachers: 'Dr. Asma Hachemi, Nadia Haddouche',
            summary_fr: "Conduire un projet informatique de l'idée à la livraison : cycles de vie, planification, suivi, clôture et post-projet.",
            summary_en: 'Run a software project from idea to delivery: life cycles, planning, tracking, closure and post-project.',
            prereq_fr: 'Aucun prérequis.', prereq_en: 'No prerequisites.',
            chapters: [
              ['Définitions et concepts du génie logiciel', 'Software-engineering definitions and concepts'],
              ['Modèles de développement : cascade, V, spirale, UP', 'Development models: waterfall, V, spiral, UP'],
              ['Avant-projet : planification et estimations', 'Pre-project: planning and estimation'],
              ['Suivi de projet : ressources, contrôle, avancement', 'Project tracking: resources, control, progress'],
              ['Clôture de projet et évaluation', 'Project closure and evaluation'],
              ['Post-projet : versions, évolutions, documentation', 'Post-project: versions, evolution, documentation'],
            ],
            links: [
              ['Atlassian — Agile coach', 'https://www.atlassian.com/agile', 'reference'],
              ['SWEBOK Guide', 'https://www.computer.org/education/bodies-of-knowledge/software-engineering', 'reference'],
            ],
          },
        ],
      },
      {
        code: 'UEM3.1', type: 'M', label_fr: 'Unité méthodologie 3.1', label_en: 'Methodology unit 3.1',
        credits: 9, coef: 4, vhs: 84,
        courses: [
          {
            code: 'PR',
            title_fr: 'Programmation Réseau',
            title_en: 'Network Programming',
            credits: 4, coef: 2, vhs: 42, c: 1.5, td: 0, tp: 1.5, continu: 0.4, examen: 0.6,
            teachers: 'Dr. Mohamed Gueroumi, Khaled Zeraoulia',
            summary_fr: "Programmer avec les sockets pour développer des applications réseau multi-clients, jusqu'au jeu vidéo en réseau.",
            summary_en: 'Socket programming to build multi-client network applications, up to networked games.',
            prereq_fr: 'Aucun prérequis.', prereq_en: 'No prerequisites.',
            chapters: [
              ['La couche transport : TCP, UDP, services', 'Transport layer: TCP, UDP, services'],
              ["Les sockets : adresses, ports, API", 'Sockets: addresses, ports, API'],
              ['Sockets TCP et UDP, serveur concurrent', 'TCP and UDP sockets, concurrent servers'],
              ['Les threads', 'Threads'],
              ['Programmation avancée : multiplexage, raw sockets', 'Advanced programming: multiplexing, raw sockets'],
              ['Threads et sockets en Java et en C sous Linux', 'Threads and sockets in Java and C on Linux'],
              ['Applications et jeux en réseau', 'Networked applications and games'],
            ],
            links: [
              ["Beej's Guide to Network Programming", 'https://beej.us/guide/bgnet/', 'reference'],
              ['Java — Networking trail', 'https://dev.java/learn/', 'reference'],
            ],
          },
          {
            code: 'SEM',
            title_fr: "Systèmes d'Exploitation Mobiles",
            title_en: 'Mobile Operating Systems',
            credits: 5, coef: 2, vhs: 42, c: 1.5, td: 0, tp: 1.5, continu: 0.4, examen: 0.6,
            teachers: 'Dr. Chafika Benzaid',
            summary_fr: "Étudier en détail les systèmes d'exploitation mobiles pour développer des applications, dont des jeux, avec maîtrise du support.",
            summary_en: 'Study mobile operating systems in depth to build applications, including games, with full command of the platform.',
            prereq_fr: "Systèmes d'exploitation.", prereq_en: 'Operating systems.',
            chapters: [
              ['Systèmes embarqués et dispositifs mobiles', 'Embedded systems and mobile devices'],
              ["Système d'exploitation mobile : caractéristiques et exemples", 'Mobile OS: characteristics and examples'],
              ['Étude de cas : Android (pile logicielle, mémoire, énergie)', 'Case study: Android (software stack, memory, power)'],
            ],
            links: [
              ['Android Developers — guides', 'https://developer.android.com/guide', 'reference'],
              ['Android Open Source Project', 'https://source.android.com/docs/core', 'reference'],
            ],
          },
        ],
      },
      {
        code: 'UED3.1', type: 'D', label_fr: 'Unité découverte 3.1', label_en: 'Discovery unit 3.1',
        credits: 3, coef: 2, vhs: 21,
        courses: [
          {
            code: 'AC',
            title_fr: 'Atelier Créatif',
            title_en: 'Creative Workshop',
            credits: 3, coef: 2, vhs: 21, c: 0, td: 0, tp: 1.5, continu: 1.0, examen: 0,
            teachers: 'Prof. Slimane Larabi, Dr. Afifa Dahmane, Dr. Amel Aissaoui',
            summary_fr: "Travailler en groupe sur un projet dans l'une des trois thématiques du master : visualisation de données, jeux vidéo, analyse d'images et de vidéo.",
            summary_en: 'Team project in one of the three master tracks: data visualisation, video games, image and video analysis.',
            prereq_fr: 'Connaissances des semestres 1, 2 et 3.', prereq_en: 'Knowledge from semesters 1, 2 and 3.',
            chapters: [
              ["Piste 1 : jeu vidéo — principe, solution, prototype, tests, rapport", 'Track 1: video game — concept, solution, prototype, testing, report'],
              ['Piste 2 : visualisation de données — problème, solution, mise en œuvre, rapport', 'Track 2: data visualisation — problem, solution, implementation, report'],
              ["Piste 3 : analyse d'images et de vidéo — problème, solution, mise en œuvre, rapport", 'Track 3: image and video analysis — problem, solution, implementation, report'],
            ],
            links: [['USTHB — Campus virtuel', 'https://campusvirtuel.usthb.dz/', 'platform']],
          },
        ],
      },
    ],
  },
  {
    number: 4,
    label_fr: 'Semestre 4',
    label_en: 'Semester 4',
    credits: 30,
    coef: 18,
    vhs: 420,
    weekly: { c: '—', td: '—', tp: '—' },
    units: [
      {
        code: 'PFE', type: 'P', label_fr: 'Projet de fin d\'études', label_en: 'Final-year project',
        credits: 30, coef: 18, vhs: 420,
        courses: [
          {
            code: 'PFE',
            title_fr: "Projet de Fin d'Études",
            title_en: 'Final-Year Project',
            credits: 30, coef: 18, vhs: 420, c: 0, td: 0, tp: 0, continu: 0, examen: 1.0,
            teachers: 'Encadrement laboratoires LRIA, LSI, RIIMA, MOVEP',
            summary_fr: "Stage en entreprise ou en laboratoire sanctionné par un mémoire et une soutenance. Structures d'accueil : USTHB, CERIST, CDTA, Mobilis et autres entreprises.",
            summary_en: 'Internship in a company or research lab, assessed by a dissertation and an oral defence. Host organisations: USTHB, CERIST, CDTA, Mobilis and other companies.',
            prereq_fr: 'Validation des semestres 1 à 3.', prereq_en: 'Semesters 1 to 3 completed.',
            chapters: [],
            links: [
              ['USTHB — PFE Licence & Master', 'https://finfo.usthb.dz/stage/-pfe-licence-master', 'platform'],
              ['USTHB — Liste des PFE', 'https://finfo.usthb.dz/stage/Liste-des-PFEs', 'platform'],
            ],
          },
        ],
      },
    ],
  },
];
